// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywczbltapzfomkdimtug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3Y3pibHRhcHpmb21rZGltdHVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTY5MTYsImV4cCI6MjA1ODY3MjkxNn0.Rw29WckOrDBiEreH4fuI6iiN-67Iql0TIbWyWaQSTqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);